{
    'name': 'Construtec Contabilidad',
    'version': '19.0.1.7.0',
    'category': 'Accounting/Accounting',
    'summary': 'Régimen fiscal y datos legales de la compañía (GT)',
    'author': 'Alex Martínez',
    'website': 'https://www.linkedin.com/in/alex-martinez',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'uom',
        'account',
        'account_debit_note',
        'purchase_stock',
        'sale',
        'construtec_sat_catalog_sync_19',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/decimal_precision_data.xml',
        'views/res_company_views.xml',
        'views/account_move_views.xml',
        'views/purchase_order_views.xml',
        'views/sale_order_views.xml',
        'views/sat_document_views.xml',
        'views/sat_import_log_views.xml',
        'views/sat_product_catalog_views.xml',
        'views/sat_categorization_rule_views.xml',
        'views/sat_retention_views.xml',
        'views/sat_retention_emitida_views.xml',
        'data/ir_cron_sat_product_catalog.xml',
    ],
    'application': False,
    'installable': True,
}
