from . import wizard_mixin
from . import report_facturacion
from . import report_libro_sueldos
from . import report_planilla_sueldos
from . import report_prestaciones
from . import report_planilla_igss
from . import report_descuentos
from . import report_informe_empleador
from . import report_liquidacion
from . import report_detalle_nomina
