{
    'name': 'Construtec Orden de Pago',
    'version': '19.0.1.9.0',
    'category': 'Accounting/Accounting',
    'summary': 'Órdenes de pago (Anticipo / Pago Directo) para conciliar facturas de varios '
               'proveedores contra pagos que no coinciden 1 a 1',
    'author': 'Alex Martínez',
    'website': 'https://www.linkedin.com/in/alex-martinez',
    'license': 'LGPL-3',
    'depends': [
        'account',
        'mail',
        'hr',
        'purchase',
        'construtec_sat_catalog_sync_19',
    ],
    'data': [
        'security/payment_order_request_security.xml',
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/account_payment_order_sequence.xml',
        'data/payment_order_sync_cron.xml',
        'data/payment_order_status_sync_cron.xml',
        'data/employee_sync_cron.xml',
        'data/partner_auto_tag_cron.xml',
        'views/account_payment_order_quote_import_wizard_views.xml',
        'views/account_payment_order_views.xml',
        'views/sat_catalog_sync_menu_views.xml',
        'views/account_payment_order_viaticos_report_views.xml',
        'views/account_move_views.xml',
        'views/account_payment_views.xml',
        'views/hr_employee_views.xml',
        'views/res_partner_views.xml',
        'views/res_partner_bank_views.xml',
        'views/res_config_settings_views.xml',
        'report/account_payment_order_report.xml',
    ],
    'application': False,
    'installable': True,
}
