from . import hr_geo
from . import hr_employee_history
from . import hr_codigo_employee
from . import hr_employee_family
from . import hr_employee_educational
from . import hr_employee_work_history
from . import hr_employee_licencia
from . import hr_version
from . import hr_employee
from . import hr_payslip_run
