from . import res_company
from . import account_move
from . import purchase_order
from . import sale_order
from . import sat_document
from . import sat_document_import
from . import sat_categorization_rule
from . import sat_import_log
from . import sat_product_catalog
from . import sat_retention
from . import sat_retention_import
from . import sat_retention_emitida
from . import sat_retention_emitida_import
