{
    'name': 'Construtec Nómina',
    'version': '19.0.1.0.0',
    'category': 'Human Resources/Payroll',
    'summary': 'Préstamos, anticipos, calificaciones, prestaciones y pago de nóminas',
    'author': 'Alex Martínez',
    'website': 'https://www.linkedin.com/in/alex-martinez',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'web',
        'hr',
        'hr_payroll',
        'hr_work_entry',
        'hr_work_entry_enterprise',
        'account',
        'account_payment',
        'hr_payroll_account',
        'account_accountant',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequences.xml',
        'data/hr_payslip_input_types.xml',
        'views/hr_version_views.xml',
        #'views/hr_work_entry_views.xml',
        'views/hr_qualification_views.xml',
        'views/hr_loan_views.xml',
        'views/salary_advance_views.xml',
        'views/hr_payslip_worked_days_wizard_views.xml',
        'views/hr_payroll_register_payment_views.xml',
        'views/hr_payroll_batchwise_register_payment_views.xml',
        'views/hr_payslip_views.xml',
        'views/hr_payslip_run_views.xml',
        'views/account_payment_views.xml',
        'views/account_move_views.xml',
        'views/hr_payslip_prestaciones_views.xml',
        'views/hr_overtime_views.xml',
        'views/hr_absence_views.xml',
        'views/hr_payslip_input_employee_views.xml',
        'views/menus.xml',
    ],
    'application': True,
    'installable': True,
}
