{
    'name': 'Construtec Reportes de Nómina',
    'version': '19.0.1.0.0',
    'category': 'Human Resources/Payroll',
    'summary': 'Constancias laborales, solicitud IRTRA, boleta de pago y reportes legales de nómina (GT)',
    'author': 'Alex Martínez',
    'website': 'https://www.linkedin.com/in/alex-martinez',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'web',
        'hr',
        'hr_payroll',
        'construtec_hr_payroll_19',
        'construtec_hr_employee_19',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/dias_laborados_data.xml',
        'views/res_company_views.xml',
        'report/report_actions.xml',
        'report/constancia_laboral_templates.xml',
        'report/solicitud_irtra_templates.xml',
        'report/voucher_templates.xml',
        'data/voucher_email_template.xml',
        'views/hr_dias_laborados_mes_views.xml',
        'wizard/report_facturacion_views.xml',
        'wizard/report_libro_sueldos_views.xml',
        'wizard/report_planilla_sueldos_views.xml',
        'wizard/report_prestaciones_views.xml',
        'wizard/report_planilla_igss_views.xml',
        'wizard/report_descuentos_views.xml',
        'wizard/report_informe_empleador_views.xml',
        'wizard/report_liquidacion_views.xml',
        'views/menus.xml',
    ],
    'application': False,
    'installable': True,
}
