{
    'name': 'Construtec Reportes Financieros',
    'version': '19.0.1.0.0',
    'category': 'Accounting/Accounting',
    'summary': 'Libro Diario, Mayor, Balance General, Estado de Resultados y demás reportes contables (GT)',
    'author': 'Alex Martínez',
    'website': 'https://www.linkedin.com/in/alex-martinez',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'web',
        'account',
        'account_accountant',
        'construtec_hr_payroll_19',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/account_account_tag_data.xml',
        'wizard/report_libro_diario_views.xml',
        'wizard/report_libro_mayor_views.xml',
        'wizard/report_conciliacion_bancaria_views.xml',
        'wizard/report_bancarizacion_views.xml',
        'wizard/report_balance_saldos_views.xml',
        'wizard/report_balance_general_views.xml',
        'wizard/report_estado_resultados_views.xml',
        'wizard/report_costo_ventas_views.xml',
        'wizard/report_costo_produccion_views.xml',
        'wizard/report_cambio_patrimonio_views.xml',
        'wizard/report_flujo_efectivo_views.xml',
        'wizard/report_libro_inventario_views.xml',
        'views/menus.xml',
    ],
    'application': False,
    'installable': True,
}
