from . import hr_version
from . import hr_employee
from . import hr_overtime
from . import hr_absence
from . import hr_payslip_input_employee
#from . import hr_work_entry
from . import hr_qualification
from . import hr_loan
from . import hr_isr_retencion
from . import salary_advance
from . import hr_payslip
#from . import hr_payslip_run
from . import hr_payslip_prestaciones
from . import account_payment
from . import account_move
